import java.util.Properties

plugins {
    id 'com.android.application'
}

Properties keystoreProperties = new Properties()
File keystorePropertiesFile = rootProject.file('key.properties')
boolean hasReleaseKeystore = keystorePropertiesFile.exists()
if (hasReleaseKeystore) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace 'com.arena.shizuku_shell_local'
    compileSdk 36
    ndkVersion '28.2.13676358'

    defaultConfig {
        applicationId 'com.arena.shizuku_shell_local'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
        externalNativeBuild { cmake { cppFlags '-std=c++17' } }
    }

    signingConfigs {
        if (hasReleaseKeystore) {
            release {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile rootProject.file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
            }
        }
    }

    buildTypes {
        release {
            // Se existir key.properties, usa a keystore release.
            // Se não existir, usa debug só para facilitar build local de quem clonar o GitHub.
            signingConfig hasReleaseKeystore ? signingConfigs.release : signingConfigs.debug
            minifyEnabled false
            shrinkResources false
        }
    }

    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a', 'arm64-v8a'
            universalApk false
        }
    }

    externalNativeBuild { cmake { path file('src/main/cpp/CMakeLists.txt'); version '3.22.1' } }
}

dependencies {
    def shizukuVersion = '13.1.5'
    implementation "dev.rikka.shizuku:api:$shizukuVersion"
    implementation "dev.rikka.shizuku:provider:$shizukuVersion"
}
